### ISSUE TITLE
Ink Res

### ISSUE THREAD

**Issue by fm360** [selicia/splat2-calc#4]
The base speed for running In enemy ink is 0.32 not 0.24

**Comment by selicia** [comment]
Thank you for reporting this! The Ink Resistance "Run in Enemy Ink" and "Jump in Enemy Ink" values have changed in v4.6 so I will be updating to those. However, because you saw a discrepancy between the v4.5 data I'm using and what you expected I'd like to investigate this.

For "Run Speed in Enemy Ink" regarding Ink Resistance I'm using the following values from Lean:
`[0.72, 0.48, 0.24]` If possible, can you share the min/max values you expected? I'll follow up with Lean to confirm I'm using the correct data.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ink Resistance Bug](https://trello.com/c/uxOemNez/20-ink-resistance-bug)

**Comment by selicia** [comment]
Lean gave me the latest (v4.6) Ink Res values: `[0.768, 0.5568, 0.24]`. This means the base speed in enemy ink should be 0.24. Do you have a source for the 0.32 value you're expecting?

**Comment by selicia** [comment]
Ink Resistance parameters have all been set to Lean's v4.6 values:
```
      "Ink Resistance": {
          "Dmg Per Frame": [0.0015, 0.00225, 0.003],
          "Run": [0.768, 0.5568, 0.24],
          "Dmg Limit": [0.2, 0.3, 0.4],
          "Shoot K": [1.0, 0.75, 0.5],
          "Jump": [1.1, 0.98, 0.8],
          "Shoot": [0.4, 0.26, 0.12],
          "Jump(story)": [1.05, 0.825, 0.6],
          "Invuln Frames": [39.0, 26.0, 0.0]
      }
```
