### ISSUE TITLE
Not all the gear items

### ISSUE THREAD

**Issue by aogummy** [selicia/splat2-calc#5]
Not all of the gear items are in the loadout calculator. Also the brand affinity is wrong on Toni Kensa and Annaki.

**Comment by selicia** [comment]
Thank you for reporting this! Updating the gear to v4.5 data is still in progress. Weapons and Shirts have been updated, but Hats and Shoes have not. Confirmed the brand affinity values are wrong and will update them as well. I'm going to open a separate issue for the brand affinity bug since it's a much smaller fix than adding the remaining new gear.

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brand Affinity Bug](https://trello.com/c/gQChgLwj/22-brand-affinity-bug)

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Missing Gear Data](https://trello.com/c/jqYSO0hD/9-add-missing-gear-data)

**Comment by selicia** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brand Affinity Bug](https://trello.com/c/gQChgLwj/22-brand-affinity-bug)

**Comment by selicia** [comment]
dea49e8e931886b073eb6a0cba0bdc81d9164e47 Fixed the brand affinities. Remaining gear will be added in a later update.

**Comment by selicia** [comment]
e4d1058d79bc6cae7ff20c9f218c0d97df5a7b05 Added all hats through v4.6. Shoes are next.

**Comment by selicia** [comment]
28e67b42949fc9ce23b1326bfed2db0df31d8465 Added all shoes through v4.6. Also added any missing gear.
